// Keep generated wave/repeat accessors rebuilt after Schedule ODS changes.
#include "ftlpu/compiler/Dialect/Schedule/IR/schedule_dialect.hpp"

#include "ftlpu/compiler/Target/lpu_target_model.hpp"

#include "mlir/IR/Builders.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/OpImplementation.h"

#include <cmath>

using namespace mlir;

// Keep the operation definitions in this translation unit synchronized with
// optional binding metadata generated by TableGen.
#include "ftlpu/compiler/Dialect/Schedule/IR/ScheduleOpsDialect.cpp.inc"

#define GET_OP_CLASSES
#include "ftlpu/compiler/Dialect/Schedule/IR/ScheduleOps.cpp.inc"

namespace ftlpu::compiler::schedule {
namespace {

LogicalResult verify_timing(Operation* op, int64_t cycle, int64_t duration)
{
    if (cycle < 0 || duration <= 0)
        return op->emitOpError("requires a non-negative cycle and positive duration");
    return success();
}

LogicalResult verify_queue_issue(Operation* op, int64_t cycle, int64_t queue,
    int64_t repeat_count, int64_t repeat_interval)
{
    if (cycle < 0 || queue < 0 || repeat_count <= 0 || repeat_interval <= 0)
        return op->emitOpError("requires non-negative cycle/queue and positive repeat fields");
    return success();
}

LogicalResult verify_stream_range(Operation* op, int64_t base, int64_t count)
{
    auto targetModel = target::LPUTargetModel::from_operation(op);
    if (failed(targetModel)) return failure();
    if (base < 0 || count <= 0
        || base + count
            > targetModel->streams().streams_per_direction)
        return op->emitOpError("stream range is outside the target direction");
    return success();
}

LogicalResult verify_mem_placement(Operation* op, DictionaryAttr placement,
    const target::LPUTargetModel& targetModel)
{
    const auto slices = placement.getAs<ArrayAttr>("slices");
    const auto base = placement.getAs<IntegerAttr>("base_row");
    const auto count = placement.getAs<IntegerAttr>("instruction_count");
    const auto stride = placement.getAs<IntegerAttr>("address_stride");
    const auto bank = placement.getAs<IntegerAttr>("bank");
    if (!slices || !base || !count || !stride)
        return op->emitOpError(
            "physical MEM placement requires slices, base_row, "
            "instruction_count, and address_stride");

    const auto& memory = targetModel.memory();
    const int64_t bankIndex = bank ? bank.getInt() : 0;
    if (bankIndex < 0 || bankIndex >= memory.banks_per_slice)
        return op->emitOpError("MEM placement bank is outside the target");
    for (Attribute attribute : slices) {
        const auto slice = dyn_cast<IntegerAttr>(attribute);
        if (!slice || slice.getInt() < 0
            || slice.getInt() >= memory.slices_per_hemisphere)
            return op->emitOpError(
                "MEM placement slice is outside the target hemisphere");
    }

    if (count.getInt() <= 0)
        return op->emitOpError(
            "MEM placement instruction_count must be positive");
    const int64_t firstRow = base.getInt();
    const int64_t lastRow = firstRow
        + (count.getInt() - 1) * stride.getInt();
    if (std::min(firstRow, lastRow) < 0
        || std::max(firstRow, lastRow) >= memory.sram_depth_rows)
        return op->emitOpError("MEM placement row range is outside SRAM: [")
            << std::min(firstRow, lastRow) << ", "
            << std::max(firstRow, lastRow) << "] not in [0, "
            << memory.sram_depth_rows << "); placement " << placement;
    return success();
}

} // namespace

LogicalResult MemReadOp::verify()
{
    if (failed(verify_timing(*this, getCycle(), getDuration()))
        || failed(verify_stream_range(*this, getStreamBase(), getStreamCount())))
        return failure();
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)
        || failed(verify_mem_placement(*this, getPlacement(), *targetModel)))
        return failure();
    auto placement = getPlacement();
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    const int64_t waveAddressStride =
        getWaveAddressStride().value_or(0);
    if (waveCount <= 0 || waveInterval <= 0)
        return emitOpError(
            "requires positive wave_count and wave_interval");
    if (auto base = placement.getAs<IntegerAttr>("base_row")) {
        const int64_t finalBase = base.getInt()
            + (waveCount - 1) * waveAddressStride;
        if (finalBase < 0
            || finalBase >= targetModel->memory().sram_depth_rows)
            return emitOpError("MEM read wave leaves physical SRAM");
    }
    auto kind = placement.getAs<StringAttr>("kind");
    if (kind && kind.getValue() == "schedule_slice") {
        if (getDirection() != "east" && getDirection() != "west")
            return emitOpError("direction must be east or west");
        auto hemisphere = placement.getAs<StringAttr>("hemisphere");
        if (!hemisphere || (hemisphere.getValue() != "east"
                            && hemisphere.getValue() != "west"))
            return emitOpError("scheduled MEM read requires a physical hemisphere");
        if (getRole() != "activation" && getRole() != "weight_i8"
            && getRole() != "vxm_fp16" && getRole() != "vxm_bf16"
            && getRole() != "vxm_fp32" && getRole() != "vxm_bypass")
            return emitOpError("contains an unsupported scheduled MEM role");
        auto slices = placement.getAs<ArrayAttr>("slices");
        if (!slices
            || static_cast<int64_t>(slices.size()) != getStreamCount())
            return emitOpError(
                "scheduled MEM read must map one slice per stream");
        if (getStreamCount() > 1) {
            auto registerIds = (*this)->getAttrOfType<ArrayAttr>(
                "register_ids");
            if (!registerIds
                || static_cast<int64_t>(registerIds.size())
                    != getStreamCount())
                return emitOpError(
                    "multi-slice MEM read requires one register_id per stream");
        }
        return success();
    }
    if (getDirection() != "east") return emitOpError("must use east streams");
    target::StreamEndpoint endpoint;
    if (getRole() == "weight") endpoint = target::StreamEndpoint::MxmWeight;
    else if (getRole() == "activation") endpoint = target::StreamEndpoint::MxmActivation;
    else return emitOpError("role must be weight or activation");
    const auto expected_count = targetModel->route_stream_count(
        target::StreamEndpoint::Mem, endpoint, target::StreamDirection::East);
    auto instruction_count = placement.getAs<IntegerAttr>("instruction_count");
    if (!expected_count || !instruction_count || getStreamCount() != *expected_count
        || getDuration() != instruction_count.getInt())
        return emitOpError("stream count or duration does not match the target model");
    return success();
}

LogicalResult MxmLoadOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (failed(verify_timing(*this, getCycle(), getDuration()))
        || failed(verify_stream_range(*this, getStreamBase(), getStreamCount())))
        return failure();
    const llvm::StringRef loadMode =
        getWeightLoadMode().value_or("supercell");
    const llvm::StringRef inputMode =
        getWeightInputMode().value_or("direct16");
    const int64_t innerColumn = getWeightInnerColumn().value_or(0);
    if (getGroupCount().value_or(1) <= 0
        || getGroupInterval().value_or(1) <= 0)
        return emitOpError(
            "requires positive group_count and group_interval");
    const int64_t expectedStreams = loadMode == "column"
        ? 2
        : inputMode == "int8_dequant_bf16"
            ? target.throughput().mxm_int8_load_streams_per_cycle
            : target.throughput().mxm_load_streams_per_cycle;
    if ((loadMode != "supercell" && loadMode != "column")
        || getStreamCount() != expectedStreams)
        return emitOpError(
            "weight load stream count does not match its mode");
    if ((loadMode == "supercell" && innerColumn != 0)
        || (loadMode == "column"
            && (innerColumn < 0
                || innerColumn >= target.throughput().lanes_per_tile)))
        return emitOpError("contains an invalid MXM inner weight column");
    if (!target.is_valid_mxm_unit(getUnitId()))
        return emitOpError("unit_id must select MXM0 or MXM1");
    if (!target.is_valid_weight_buffer(getWeightBuffer()))
        return emitOpError("weight_buffer must select buffer 0 or 1");
    if (inputMode != "direct16"
        && inputMode != "int8_dequant_bf16")
        return emitOpError(
            "weight_input_mode must be direct16 or int8_dequant_bf16");
    return success();
}

LogicalResult MxmComputeOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (failed(verify_timing(*this, getCycle(), getDuration()))) return failure();
    if (getM() <= 0 || getN() <= 0 || getK() <= 0)
        return emitOpError("matrix dimensions must be positive");
    if (!target.is_valid_mxm_unit(getUnitId())
        || !target.is_valid_weight_buffer(getWeightBuffer()))
        return emitOpError("contains an invalid MXM unit or weight buffer");
    const llvm::StringRef dataFormat =
        getDataFormat().value_or("fp16");
    if (dataFormat != "fp16" && dataFormat != "bf16")
        return emitOpError("data_format must be fp16 or bf16");
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    if (waveCount <= 0 || waveInterval <= 0)
        return emitOpError(
            "requires positive wave_count and wave_interval");
    if (getDuration() != target.mxm_compute_issue_cycles(getM())
        || getResultCycle() != getCycle() + target.mxm_first_result_latency()
        || getResultDuration() != target.mxm_result_window_cycles(getM()))
        return emitOpError("compute or result timing does not match the MXM pipeline");
    if (failed(verify_stream_range(*this, getActivationStreamBase(), 1))
        || failed(verify_stream_range(*this, getOutputStreamBase(), 4)))
        return failure();
    return success();
}

LogicalResult VxmOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    const int64_t chainDepth = getChainDepth().value_or(8);
    if (getCycleAttr().getInt() < 0
        || !target.is_valid_vxm_alu(getQueue()) || getQueue() >= 8
        || (chainDepth != 2 && chainDepth != 4 && chainDepth != 8)
        || getRepeatCount() <= 0 || getRepeatInterval() <= 0)
        return emitOpError("contains invalid cycle, ALU queue, or repeat metadata: cycle=")
            << getCycle() << ", queue=" << getQueue()
            << ", opcode=" << getOpcode()
            << ", lhs=" << getLhsKind() << "(" << getLhsIndex() << ")"
            << ", rhs=" << getRhsKind() << "(" << getRhsIndex() << ")"
            << ", output_stream=" << getOutputStream()
            << ", chain_depth=" << chainDepth
            << ", repeat_count=" << getRepeatCount()
            << ", repeat_interval=" << getRepeatInterval();
    if (getAccumulatorReset().value_or(false)
        && !getAccumulatorWrite().value_or(false))
        return emitOpError(
            "accumulator_reset requires accumulator_write");
    if (!getAccumulatorWrite().value_or(false)
        && !getAccumulatorEmit().value_or(true))
        return emitOpError(
            "accumulator_emit=false requires accumulator_write");
    if (getLocalScalarWrite().value_or(false)
        && getAccumulatorWrite().value_or(false))
        return emitOpError(
            "local_scalar_write cannot be combined with accumulator_write");
    const auto opcode = getOpcode();
    if (opcode != "pass" && opcode != "bypass" && opcode != "cast"
        && opcode != "add" && opcode != "subtract"
        && opcode != "multiply" && opcode != "fma" && opcode != "fms"
        && opcode != "negate"
        && opcode != "max" && opcode != "exp"
        && opcode != "reciprocal" && opcode != "rsqrt")
        return emitOpError("contains an unsupported hardware VXM opcode");
    const auto valid_kind = [](StringRef kind) {
        return kind == "alu" || kind == "stream_i8"
            || kind == "stream_f16" || kind == "stream_bf16"
            || kind == "stream_f32"
            || kind == "immediate" || kind == "previous"
            || kind == "original" || kind == "auxiliary"
            || kind == "accumulator" || kind == "feedback";
    };
    if (!valid_kind(getLhsKind()) || !valid_kind(getRhsKind()))
        return emitOpError("contains an invalid operand kind");
    const auto isStreamOperand = [](StringRef kind) {
        return kind == "stream_i8" || kind == "stream_f16"
            || kind == "stream_bf16" || kind == "stream_f32";
    };
    const auto validStreamSource = [&](StringRef kind,
                                       llvm::StringRef attributeName) {
        const auto source =
            (*this)->getAttrOfType<mlir::StringAttr>(attributeName);
        if (!source) return true;
        return isStreamOperand(kind)
            && (source.getValue() == "local"
                || source.getValue() == "east"
                || source.getValue() == "west");
    };
    if (!validStreamSource(getLhsKind(), "lhs_stream_source")
        || !validStreamSource(getRhsKind(), "rhs_stream_source"))
        return emitOpError(
            "stream source must be local/east/west and requires a stream operand");
    const auto valid_operand = [&](StringRef kind, int64_t index) {
        if (kind == "immediate") return index == 0;
        if (kind == "previous" || kind == "original"
            || kind == "auxiliary" || kind == "accumulator"
            || kind == "feedback")
            return index == 0;
        if (kind == "alu") return index == getQueue() - 1;
        if (kind == "stream_i8" || kind == "stream_f16"
            || kind == "stream_bf16" || kind == "stream_f32")
            return index >= 0
                && index + 1 < target.streams().encoded_streams;
        return false;
    };
    if (!valid_operand(getLhsKind(), getLhsIndex())
        || !valid_operand(getRhsKind(), getRhsIndex()))
        return emitOpError("contains an invalid operand index: queue=")
            << getQueue() << ", opcode=" << getOpcode()
            << ", lhs=" << getLhsKind() << "(" << getLhsIndex() << ")"
            << ", rhs=" << getRhsKind() << "(" << getRhsIndex() << ")";
    const bool fused = opcode == "fma" || opcode == "fms";
    const bool chainHead = getQueue() % chainDepth == 0;
    if (fused
        && (chainHead || (getQueue() - 1) % chainDepth != 0
            || !isStreamOperand(getLhsKind())
            || !isStreamOperand(getRhsKind())))
        return emitOpError(
            "fma/fms must immediately follow a VXM chain head and use two stream operands");
    const int64_t output = getOutputStreamAttr().getInt();
    if (output < -1 || output >= target.streams().encoded_streams)
        return emitOpError("contains an invalid output stream");
    if ((getInputHemisphere() != "east" && getInputHemisphere() != "west")
        || (getOutputHemisphere() != "east" && getOutputHemisphere() != "west"))
        return emitOpError("hemisphere must be east or west");
    return success();
}

LogicalResult MxmAccumulateOp::verify()
{
    if (getRepeatCount() <= 0 || getRepeatInterval() <= 0
        || getAccumulatorAddress() < 0 || getAccumulatorAddress() >= 8192
        || getAccumulatorStride() <= 0 || getAccumulatorStride() > 4095)
        return emitOpError("contains invalid accumulation timing or stride: cycle=")
            << getCycle() << ", repeat_count=" << getRepeatCount()
            << ", repeat_interval=" << getRepeatInterval()
            << ", accumulator_address=" << getAccumulatorAddress()
            << ", accumulator_stride=" << getAccumulatorStride();
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    if (!targetModel->is_valid_mxm_unit(getUnitId()))
        return emitOpError("contains invalid MXM unit_id");
    if (getDestination() != "local" && getDestination() != "stream")
        return emitOpError("destination must be local or stream");
    const llvm::StringRef outputFormat =
        getAccumulatorOutputFormat().value_or("fp32");
    if (outputFormat != "fp32" && outputFormat != "bf16")
        return emitOpError(
            "accumulator_output_format must be fp32 or bf16");
    if (getDestination() == "local" && outputFormat != "fp32")
        return emitOpError(
            "a retained accumulator value must keep FP32 format");
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    const int64_t finalAddress = getAccumulatorAddress()
        + (waveCount - 1)
            * getWaveAccumulatorAddressStride().value_or(0);
    if (waveCount <= 0 || waveInterval <= 0
        || finalAddress < 0 || finalAddress >= 8192)
        return emitOpError("contains an invalid accumulator wave");
    if (failed(verify_stream_range(*this, getStreamBase(), getStreamCount())))
        return failure();
    return success();
}

LogicalResult MxmAccumulatorReadOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (getCycle() < 0 || !target.is_valid_mxm_unit(getUnitId())
        || getAccumulatorAddress() < 0 || getAccumulatorAddress() >= 8192)
        return emitOpError("contains an invalid MXM accumulator read field");
    if (getOutputStreamBase() < 0
        || getOutputStreamBase()
                + target.throughput().mxm_result_streams
                - 1
            >= target.streams().streams_per_direction)
        return emitOpError("contains an invalid accumulator output stream");
    if (getInput().getType() != getOutput().getType())
        return emitOpError("must preserve the logical accumulator value type");
    return success();
}

LogicalResult MemWriteOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (failed(verify_timing(*this, getCycle(), getDuration()))
        || failed(verify_stream_range(*this, getStreamBase(), getStreamCount())))
        return failure();
    auto placement = getPlacement();
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    const int64_t waveAddressStride =
        getWaveAddressStride().value_or(0);
    if (waveCount <= 0 || waveInterval <= 0)
        return emitOpError(
            "requires positive wave_count and wave_interval");
    if (auto base = placement.getAs<IntegerAttr>("base_row")) {
        const int64_t finalBase = base.getInt()
            + (waveCount - 1) * waveAddressStride;
        if (finalBase < 0 || finalBase >= target.memory().sram_depth_rows)
            return emitOpError()
                << "MEM write wave leaves physical SRAM: base="
                << base.getInt() << ", wave_count=" << waveCount
                << ", wave_address_stride=" << waveAddressStride
                << ", final_base=" << finalBase
                << ", depth=" << target.memory().sram_depth_rows
                << ", cycle=" << getCycle()
                << ", duration=" << getDuration()
                << ", stream_base=" << getStreamBase()
                << ", stream_count=" << getStreamCount()
                << ", placement=" << placement;
    }
    if (failed(verify_mem_placement(*this, placement, target)))
        return failure();
    auto kind = placement.getAs<StringAttr>("kind");
    auto hemisphere = placement.getAs<StringAttr>("hemisphere");
    if (!hemisphere) hemisphere = getAddress().getAs<StringAttr>("hemisphere");
    auto slices = placement.getAs<ArrayAttr>("slices");
    auto instructionCount = placement.getAs<IntegerAttr>("instruction_count");
    const bool exactPhysicalWrite = hemisphere && slices && instructionCount
        && (hemisphere.getValue() == "east" || hemisphere.getValue() == "west")
        && instructionCount.getInt() == getDuration()
        && static_cast<int64_t>(slices.size()) == getStreamCount();
    if ((kind && kind.getValue() == "schedule_slice") || exactPhysicalWrite) {
        if (getDirection() != "east" && getDirection() != "west")
            return emitOpError("direction must be east or west");
        if (!exactPhysicalWrite)
            return emitOpError("scheduled MEM write does not match its physical slices");
        return success();
    }
    const bool vxm = static_cast<bool>(getInput().getDefiningOp<VxmOp>());
    auto instruction_count = placement.getAs<IntegerAttr>("instruction_count");
    const auto expected_direction = vxm ? "east" : "west";
    const int64_t expected_streams = vxm ? 1 : target.throughput().mxm_result_streams;
    if (getDirection() != expected_direction || getStreamCount() != expected_streams
        || !instruction_count || getDuration() != instruction_count.getInt())
        return emitOpError("stream count or duration does not match the result route");
    return success();
}

LogicalResult BindingOp::verify()
{
    if (getIndex() < 0 || getBytes() <= 0)
        return emitOpError(
            "requires a non-negative index and positive byte size");
    if (getAccess() != "input" && getAccess() != "output"
        && getAccess() != "internal")
        return emitOpError("access must be input, output, or internal");
    if (getAccess() == "input") {
        if (getSource().size() != 1
            || getSource().front().getType() != getValue().getType())
            return emitOpError(
                "input binding requires one type-matched source");
    } else if (!getSource().empty()) {
        return emitOpError(
            "output and internal bindings must not have an SSA source");
    }
    if (const auto initializer = getInitializer()) {
        if (*initializer != "none" && *initializer != "zero"
            && *initializer != "causal_mask"
            && *initializer != "rope_table")
            return emitOpError("contains an unsupported initializer");
        if (getAccess() != "internal" && *initializer != "none")
            return emitOpError(
                "only internal bindings may have an initializer");
        if (*initializer == "rope_table") {
            const auto config = getInitializerConfig();
            if (!config
                || !config->getAs<FloatAttr>("theta")
                || !config->getAs<IntegerAttr>("head_dim"))
                return emitOpError(
                    "rope_table initializer requires theta and head_dim");
        }
    }
    if (!getPlacement().getAs<ArrayAttr>("slices")
        || !getPlacement().getAs<IntegerAttr>("base_row")
        || !getPlacement().getAs<IntegerAttr>("instruction_count"))
        return emitOpError("requires a physical MEM placement");
    return success();
}

LogicalResult TimelineOp::verify()
{
    if (getName().empty() || getStart() < 0 || getEnd() <= getStart())
        return emitOpError(
            "requires a name and a positive cycle interval");
    return success();
}

LogicalResult MemTransferOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    const int64_t waveAddressStride = getWaveAddressStride().value_or(0);
    if (failed(verify_queue_issue(*this, getCycle(), getSlice(),
            getRepeatCount(), getRepeatInterval())))
        return failure();
    if (getHemisphere() < 0
        || getHemisphere() >= target.memory().hemispheres)
        return emitOpError("hemisphere is outside the target: ")
            << getHemisphere() << " not in [0, "
            << target.memory().hemispheres << ")";
    if (getSlice() < 0
        || getSlice() >= target.memory().slices_per_hemisphere)
        return emitOpError("slice is outside the target hemisphere: ")
            << getSlice() << " not in [0, "
            << target.memory().slices_per_hemisphere << ")";
    const int64_t bank = getBank().value_or(0);
    if (bank < 0 || bank >= target.memory().banks_per_slice)
        return emitOpError("bank is outside the target: ")
            << bank << " not in [0, "
            << target.memory().banks_per_slice << ")";
    const int64_t memoryRows = target.memory().sram_depth_rows;
    if (getAddress() < 0 || getAddress() >= memoryRows)
        return emitOpError("address is outside the target SRAM: ")
            << getAddress() << " not in [0, " << memoryRows << ")";
    if (getPackedStream() < 0
        || getPackedStream() >= target.streams().encoded_streams)
        return emitOpError("packed stream is outside the target: ")
            << getPackedStream() << " not in [0, "
            << target.streams().encoded_streams << ")";
    if (waveCount <= 0 || waveInterval <= 0)
        return emitOpError("requires positive wave_count and wave_interval");
    const int64_t corners[] = {
        getAddress(),
        getAddress() + (getRepeatCount() - 1) * getAddressStride(),
        getAddress() + (waveCount - 1) * waveAddressStride,
        getAddress() + (waveCount - 1) * waveAddressStride
            + (getRepeatCount() - 1) * getAddressStride(),
    };
    if (llvm::any_of(corners,
            [&](int64_t address) {
                return address < 0 || address >= memoryRows;
            }))
        return emitOpError("wave/repeat address range is outside SRAM");
    if (getOpcode() != "read" && getOpcode() != "write"
        && getOpcode() != "write_tap" && getOpcode() != "accumulate")
        return emitOpError(
            "opcode must be read, write, write_tap, or accumulate");
    return success();
}

LogicalResult MxmIssueOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (failed(verify_queue_issue(*this, getCycle(), getUnitId(), getRepeatCount(), getRepeatInterval()))
        || !target.is_valid_mxm_unit(getUnitId()) || !target.is_valid_weight_buffer(getWeightBuffer())
        || getWeightColumn() < 0 || getWeightColumn() >= target.throughput().tile_rows)
        return emitOpError("contains an invalid MXM issue: cycle=")
            << getCycle() << ", unit_id=" << getUnitId()
            << ", weight_buffer=" << getWeightBuffer()
            << ", weight_column=" << getWeightColumn()
            << ", activation_stream_base=" << getActivationStreamBase()
            << ", output_stream_base=" << getOutputStreamBase();
    if (getOpcode() != "iw" && getOpcode() != "compute"
        && getOpcode() != "accumulator_read")
        return emitOpError("opcode must be iw, compute, or accumulator_read");
    const int64_t waveCount = getWaveCount().value_or(1);
    const int64_t waveInterval = getWaveInterval().value_or(1);
    const int64_t waveColumnStride =
        getWaveWeightColumnStride().value_or(0);
    const int64_t waveAccumulatorStride =
        getWaveAccumulatorAddressStride().value_or(0);
    const int64_t groupCount = getGroupCount().value_or(1);
    const int64_t groupInterval = getGroupInterval().value_or(1);
    const int64_t finalWeightColumn = getWeightColumn()
        + (waveCount - 1) * waveColumnStride;
    if (waveCount <= 0 || waveInterval <= 0
        || groupCount <= 0 || groupInterval <= 0
        || finalWeightColumn < 0
        || finalWeightColumn >= target.throughput().tile_rows)
        return emitOpError("contains an invalid MXM issue wave");
    if (waveColumnStride != 0 && waveAccumulatorStride != 0)
        return emitOpError(
            "an MXM issue wave may induct only one hardware field");
    if (getOpcode() == "iw" && waveAccumulatorStride != 0)
        return emitOpError(
            "an iw wave cannot induct the MXM accumulator address");
    if (getOpcode() != "iw" && waveColumnStride != 0)
        return emitOpError(
            "only an iw wave may induct the MXM weight column");
    const llvm::StringRef dataFormat =
        getDataFormat().value_or("fp16");
    if (dataFormat != "fp16" && dataFormat != "bf16")
        return emitOpError("data_format must be fp16 or bf16");
    const llvm::StringRef accumulatorOutputFormat =
        getAccumulatorOutputFormat().value_or("fp32");
    if (accumulatorOutputFormat != "fp32"
        && accumulatorOutputFormat != "bf16")
        return emitOpError(
            "accumulator_output_format must be fp32 or bf16");
    const llvm::StringRef loadMode =
        getWeightLoadMode().value_or("supercell");
    const int64_t innerColumn = getWeightInnerColumn().value_or(0);
    if (loadMode != "supercell" && loadMode != "column")
        return emitOpError(
            "weight_load_mode must be supercell or column");
    if (getOpcode() != "iw" && loadMode != "supercell")
        return emitOpError(
            "only iw may use column weight loading");
    if ((loadMode == "supercell" && innerColumn != 0)
        || (loadMode == "column"
            && (innerColumn < 0
                || innerColumn >= target.throughput().lanes_per_tile)))
        return emitOpError("contains an invalid MXM inner weight column");
    const int64_t accumulatorRows =
        target.throughput().mxm_accumulator_blocks
        * target.throughput().mxm_rows;
    const int64_t finalAccumulatorAddress = getAccumulatorAddress()
        + (waveCount - 1) * waveAccumulatorStride;
    if (getAccumulatorAddress() < 0
        || getAccumulatorAddress() >= accumulatorRows
        || finalAccumulatorAddress < 0
        || finalAccumulatorAddress >= accumulatorRows
        || getAccumulatorRowStride() <= 0)
        return emitOpError(
            "contains an invalid MXM accumulator address or stride: address=")
            << getAccumulatorAddress()
            << ", stride=" << getAccumulatorRowStride();
    if (getAccumulatorDestination() != "sram"
        && getAccumulatorDestination() != "stream")
        return emitOpError("accumulator_destination must be sram or stream");
    const llvm::StringRef inputMode =
        getWeightInputMode().value_or("direct16");
    if (inputMode != "direct16"
        && inputMode != "int8_dequant_bf16")
        return emitOpError(
            "weight_input_mode must be direct16 or int8_dequant_bf16");
    const int64_t weightStreams = loadMode == "column"
        ? inputMode == "int8_dequant_bf16" ? 1 : 2
        : inputMode == "int8_dequant_bf16"
        ? target.throughput().mxm_int8_load_streams_per_cycle
        : target.throughput().mxm_load_streams_per_cycle;
    const int64_t weightStreamBase = getWeightStreamBase().value_or(0);
    if (weightStreamBase < 0
        || weightStreamBase + weightStreams
            > target.streams().streams_per_direction)
        return emitOpError("contains an invalid MXM weight stream range");
    return success();
}

LogicalResult MxmDequantOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    if (getCycle() < 0
        || !targetModel->is_valid_mxm_unit(getUnitId())
        || getRepeatCount() <= 0 || getRepeatInterval() <= 0
        || getWaveCount().value_or(1) <= 0
        || getWaveInterval().value_or(1) <= 0
        || (getScaleBinding() && *getScaleBinding() < 0)
        || !std::isfinite(getScaleAttr().getValueAsDouble()))
        return emitOpError(
            "contains an invalid MXM dequant schedule field");
    return success();
}

LogicalResult SxmOp::verify()
{
    auto targetModel = target::LPUTargetModel::from_operation(*this);
    if (failed(targetModel)) return failure();
    const auto& target = *targetModel;
    if (getCycle() < 0 || getHemisphere() < 0
        || getHemisphere() >= target.memory().hemispheres)
        return emitOpError("contains an invalid SXM queue selector");
    if (getRepeatCount().value_or(1) <= 0
        || getRepeatInterval().value_or(1) <= 0)
        return emitOpError("repeat count and interval must be positive");
    if (getOpcode() != "transpose" && getOpcode() != "permute")
        return emitOpError("opcode must be transpose or permute");
    if (getOutputRow()
        && (*getOutputRow() < 0
            || *getOutputRow() >= target.throughput().lanes_per_tile))
        return emitOpError("output_row must be in the physical lane range");
      if (getInputRow()
          && (*getInputRow() < 0
              || *getInputRow() >= target.throughput().lanes_per_tile))
          return emitOpError("input_row must be in the physical lane range");
      if (getOutputTile()
          && (*getOutputTile() < 0
              || *getOutputTile() >= target.throughput().tile_rows))
          return emitOpError("output_tile must be in the physical tile range");
    const int64_t physicalWidth =
        2 * target.throughput().lanes_per_tile;
    const int64_t sourceWidth = getInputRow() ? 2 : physicalWidth;
    if (getSourceStreams().size() != sourceWidth
        || getDestinationStreams().size() != physicalWidth
        || getPermuteMap().size() != 32)
        return emitOpError()
            << "requires " << sourceWidth << " source and "
            << physicalWidth
            << " destination byte streams and a 32-lane map";
    return success();
}

void ScheduleDialect::initialize()
{
    addOperations<
#define GET_OP_LIST
#include "ftlpu/compiler/Dialect/Schedule/IR/ScheduleOps.cpp.inc"
        >();
}

} // namespace ftlpu::compiler::schedule
